name: fermipy
channels:
  - fermi
  - conda-forge
dependencies:
  - python
  - pyyaml
  - numpy>=1.16
  - scipy<1.12
  - astropy<=6.0.0
  - matplotlib>=3.3
  - healpy
  - astropy-healpix
  - gammapy>=1.0
  - fermitools>=2.2.0
