name: Docs
on: [push, release]

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fermiPy/fermipy-extra
          path: fermipy-extra
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          activate-environment: fermipy
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false
      - name: Install additional packages
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupytext jupyterthemes jupyter_latex_envs
          pip install -e .
      - name: Execute the notebooks
        #shell: bash -l {0}
        run: |
          ls
          ls fermipy-extra/notebooks
          jupytext --execute fermipy-extra/notebooks/file_function_examples.ipynb
          mkdir docs/notebooks
          mv fermipy-extra/notebooks/file_function_examples.ipynb docs/notebooks/
          ls docs/notebooks
      # - name: Create function gallery
      #   #shell: bash -l {0}
      #   run: |
      #     # move to the scripts directory
      #     cd scripts


      #     # now generate the function docs
      #     python generate_func_docs.py

      #     cd ..

      #     ls docs/notebooks
          
      - uses: actions/upload-artifact@v4
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs/notebooks
      # - name: Sleep for 10 min
      #   uses: juliangruber/sleep-action@v1
      #   with:
      #     time: 10m

      # - name: Trigger RTDs build
      #   uses: dfm/rtds-action@main
      #   with:
      #     webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
      #     webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
      #     commit_ref: ${{ github.ref }}